name: Connect to EC2

on:
  workflow_dispatch:  # manually trigger from GitHub UI

jobs:
  ssh-connect:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Connect to EC2 via SSH and run a command
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          echo "Connected to EC2!"
          uname -a
          # run any other command here
