name: Build and Deploy API to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Enable corepack
      run: |
        corepack enable
        corepack prepare pnpm@latest --activate

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build the app
      run: pnpm run build

    - name: Copy `dist/` folder to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "dist/"
        target: "/home/${{ secrets.EC2_USER }}/app/dist"

    - name: Post-deploy script on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "✅ Code deployed to ~/app/dist/"
          # Optionally restart Node app
          # pm2 restart your-app || pm2 start ~/app/dist/index.js --name your-app
