name: Test SSH Connection to EC2

on:
  workflow_dispatch: # manual trigger

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        printf "%s\n" "${{ secrets.EC2_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful!'"
